from application.model.entity.noticia import Noticia
from application.model.entity.comentario import Comentario
from application.model.dao import comentario
import random

class NoticiaDao:
    def __init__(self):
        self.noticia = [
            Noticia(0, "Com Covid em alta, Xangai decide impor confinamentos temporários por setor",
                "A maior cidade da China irá confinar por cinco dias sua metade leste a partir de segunda-feira; depois, fará o mesmo com a parte oeste. O objetivo é reduzir as contaminações por Covid, que vem crescendo devido à proliferação da variante ômicron",
                "A cidade de Xangai vai impor confinamentos por setores para tentar reduzir a curva de contágio da Covid-19 que volta a atingir a China, devido à variante ômicron - informaram autoridades locais neste domingo (27). Com 25 milhões de habitantes, a maior cidade da China vai confinar sua metade leste por cinco dias, a partir desta segunda-feira (28), para fazer testes. A partir de 1º de abril, fará o mesmo com a parte oeste.",
                "https://t2.tudocdn.net/516720?w=1920&h=1080",
                "RJ",
                "27/03/2022",
                "560.346"),
            Noticia(1, "Covid-19: Mapa 'todo verde' pela 1ª vez em 20 meses mostra que UTIs estão fora da zona de alerta",
                "É a primeira vez que isso ocorre desde que a Fundação passou a monitorar as taxas de ocupação de leitos, em julho de 2020. Dados são referentes às Semanas Epidemiológicas (SE) 10 e 11 de 2022, que abrange o período de 6 a 19 de março.",
                "Pela primeira vez desde julho de 2020, taxa de ocupação de leitos de UTI Covid-19 para adultos no Brasil está fora da zona de alerta, com taxas inferiores a 60%, informou a Fiocruz nesta sexta-feira (25). O mapa do Brasil aparece totalmente em “verde” (alerta baixo) pela primeira vez desde que a Fundação passou a monitorar as taxas de ocupação de leitos de UTI/SRAG e Covid-19 para adultos no sistema público de saúde.",
                "https://s2.glbimg.com/tUKMliFNLMxosXp2Pd_7f-CwmBA=/0x0:1074x654/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/f/A/a2V6JqTGajPXArsukSAw/fiocruz.png",
                "AL",
                "25/03/2022",
                "539.871"),
            Noticia(2, "Vacinação contra a Covid: 74,38% da população está totalmente imunizada",
                "Mais da metade das crianças tomou a primeira dose. Os dados foram coletados pelo consórcio de veículos de imprensa nesta sexta (25).",
                "Os dados do consórcio de veículos de imprensa desta sexta-feira (25) mostram que 159.786.755 pessoas estão totalmente imunizadas. Este número representa 74,38% da população total do país. A dose de reforço foi aplicada em 74.866.346 pessoas, o que corresponde a 34,85% da população. A população com 5 anos de idade ou mais (ou seja, a população vacinável) que está parcialmente imunizada é de 87,63% e a população com 5 anos ou mais que está totalmente imunizada é de 79,83%. A dose de reforço foi aplicada em 46,28% da população com 18 anos de idade ou mais, faixa de idade que atualmente pode receber o reforço da vacinação.",
                "https://especiais.gazetadopovo.com.br/wp-content/uploads/sites/19/2021/06/29141238/vacina-brasil-covid-19.jpg",
                "RN",
                "25/03/2022",
                "520.898"),
            Noticia(3, "Brasil registra mais 290 mortes por Covid; média móvel continua abaixo de 400",
                "País tem 657.157 óbitos e 29.613.732 casos registrados do novo coronavírus desde o início da pandemia, segundo dados reunidos pelo consórcio de veículos de imprensa. Média aponta 322 vítimas por dia na última semana.",
                "O Brasil registrou neste sábado (19) 290 mortes pela Covid-19 nas últimas 24 horas, totalizando 657.157 óbitos desde o início da pandemia. Com isso, a média móvel de mortes nos últimos 7 dias é de 309 --a menor desde 24 de janeiro (quando estava em 307), abaixo de 400 pelo 5º dia. Em comparação à média de 14 dias atrás, a variação foi de - 28% indicando tendência de queda nos óbitos decorrentes da doença. GO, DF, AC, SE, RR, PI, AP, AM não registraram mortes.",
                "https://cdn.spacemoney.com.br/upload/dn_arquivo/2021/09/agenciabr.jpg",
                "PA",
                "19/03/2022",
                "510.436"),
            Noticia(4, "Vacina contra covid: quem pode tomar 4ª dose",
                "O governo federal confirmou que idosos com mais de 80 anos terão direito a mais uma aplicação do imunizante que protege contra os efeitos do coronavírus. Entenda como a nova etapa da campanha funcionará.",
                "O Ministério da Saúde anunciou na quarta-feira (23) que os brasileiros com mais de 80 anos terão direito a uma quarta dose da vacina que protege contra a covid-19. A quarta dose já estava garantida desde dezembro de 2021 para indivíduos com mais de 18 anos que apresentam problemas no sistema imunológico.",
                "https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2021/10/vacina_covid_19_df.jpg?w=876&h=484&crop=1",
                "AC",
                "24/03/2022",
                "495.231"),
            Noticia(5, "Máscaras servem para proteção contra o novo coronavírus?",
                "Apesar de ter sido adotada por muitas pessoas, elas não são necessárias para a população em geral no atual estágio da epidemia, segundo especialistas. Entenda.",
                "Apesar de muita gente ter passado a usar máscaras para se tentar se prevenir do Covid-19, doença causada pelo novo coronavírus, especialistas dizem que o uso delas não é necessário para a população em geral no atual estágio da epidemia. A recomendação da Organização Mundial de Saúde (OMS) é que somente as pessoas que estão doentes usem máscaras, afirmou a epidemiologista Maria van Kerkhove, líder técnica de programas de emergência da entidade.",
                "https://i2.wp.com/jornal.usp.br/wp-content/uploads/2022/01/20220124_mascara.jpg?resize=1200%2C635&ssl=1",
                "SP",
                "27/02/2020",
                "475.870"),
            Noticia(6, "Acre recebe mais 33,2 mil doses de vacina contra a Covid-19",
                "Na tarde desta segunda-feira, 20, o governo do Acre recebeu do Ministério da Saúde mais 33.290 doses de vacina contra a Covid-19, sendo 25.740 doses da fabricante Pfizer, 7.250 Fiocruz/AstraZeneca e 300 da Janssen (dose única).",
                "Os imunizantes da Pfizer e Fiocruz/AstraZeneca serão destinados para aplicação de segundas doses. O sucesso das ações de imunização é refletido no baixo número de novos casos e óbitos. O Acre tem, hoje, 79,31% de sua população vacinada e já aplicou 727.789 doses. A maioria dos municípios estão com cobertura vacinal superior a 60%.“Nosso objetivo é zerar esses números, o que só será possível com 100% da cobertura vacinal e, para tanto, precisamos que a população atenda o nosso chamado, se disponibilize para receber as duas doses, para que juntos possamos vencer o coronavírus”, salientou a secretária de Estado de Saúde, Paula Mariano.",
                "https://agencia.ac.gov.br/wp-content/uploads/2021/09/033e59eb-ba83-4555-af4d-e13391dbff6c.jpg",
                "AC",
                "21/09/2021",
                "469.253"),
            Noticia(7, "Estado inicia distribuição de mais 24.142 doses de vacinas contra a Covid-19",
                "Imunizantes CoronaVac e Pfizer chegaram ao Estado na quinta (8) e nesta sexta (9).",
                "Uma nova remessa com 24.142 doses de vacinas contra a Covid-19 começou a ser distribuída para os 102 municípios alagoanos pelo Governo do Estado, por meio da Secretaria de Estado da Saúde (Sesau). Os imunizantes CoronaVac e Pfizer chegaram a Alagoas nessa quinta-feira (8) e na madrugada desta sexta-feira (9), enviados pelo Ministério da Saúde (MS).",
                "http://www.agenciaalagoas.al.gov.br/media/k2/items/cache/50d01451561b912673a155595d633db5_L.jpg",
                "AL",
                "09/07/2021",
                "450.781"),
            Noticia(8,"Covid-19: DF registra 260 novos casos e mais 3 mortes",
                "Brasília soma 692.240 infectados e 11.582 óbitos, desde início da pandemia. Taxa de transmissão do vírus está em 0,64; quando menor do que 1, indica queda nas infecções.",
                "O Distrito Federal registrou 260 novos casos conhecidos de Covid-19 e mais 3 mortes pela doença, nesta quarta-feira (30). Todos os óbitos ocorreram na última segunda-feira (28). Desde o início da pandemia, 11.582 pessoas perderam a vida e 692.240 foram infectadas pelo novo coronavírus em Brasília. Segundo a Secretaria de Saúde, 98,2% dos pacientes de Covid, no DF, estão recuperados.",
                "https://s2.glbimg.com/vXhZf75Usm78Zu132f0GVFldXGQ=/0x0:2048x1360/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/5/R/p7URBSStCnp4ibnXTnpQ/50736999386-4c973e137d-k.jpg",
                "DF",
                "30/03/2022",
                "420.125"),
            Noticia(9,"DF começa a aplicar 4ª dose da vacina contra Covid em idosos acima de 80 anos na sexta-feira, diz Ibaneis",
                "Governador fez anúncio por meio de rede social, durante tarde desta quarta-feira (30). Medida é possível com chegada de quase 50 mil doses de imunizante da Pfizer.",
                "O governador do Distrito Federal, Ibaneis Rocha (MDB), anunciou por meio de uma rede social, durante a tarde desta quarta-feira (30), que a 4ª dose da vacina (a segunda dose de reforço) contra Covid-19, para idosos acima de 80 anos, começa a ser aplicada a partir de sexta-feira (1º). A aplicação do reforço foi recomendada pelo Ministério da Saúde, no dia 23 de março, e publicada em uma nota técnica. Segundo o ministério, a aplicação deve ser feita quatro meses após a primeira dose de reforço. Antes da orientação, a chamada quarta dose só era aplicada em pessoas – incluindo adolescentes - com imunossupressão. Ou seja, os grupos com problemas no sistema imunológico.",
                "https://s2.glbimg.com/vRaDukOVWdFX5FCVtHyTIAGOFOE=/0x0:1500x1000/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/x/3/loebxpSqGarxjApp5f4g/whatsapp-image-2022-03-26-at-18.33.16.jpeg",
                "DF",
                "30/03/2022",
                "418.453"),
            Noticia(10,"Goiás confirma 1.277.991 casos de Covid-19 e 26.225 mortes",
                "No Estado, há 769.901 casos e 351 óbitos suspeitos em investigação e 317.266 casos já foram descartados. Levantamento realizado pela SES-GO apurou que, referente à primeira dose, foram aplicadas 5.676.139 doses das vacinas contra a Covid-19",
                "A Secretaria de Estado da Saúde de Goiás (SES-GO) informa que há 1.277.991 casos de doença pelo coronavírus 2019 (Covid-19) no território goiano. No Estado, há 769.901 casos suspeitos em investigação e 317.266 casos já foram descartados. Há 26.225 óbitos confirmados de Covid-19 em Goiás, até o momento, o que significa uma taxa de letalidade de 2,05%. Há 351 óbitos suspeitos que estão em investigação. Levantamento realizado pela SES-GO apurou que, referente à primeira dose, foram aplicadas 5.676.139 doses das vacinas contra a Covid-19 em todo o Estado. Em relação à segunda dose e à dose única, foram vacinadas 4.929.963 pessoas, e 1.827.320 pessoas já receberam a dose de reforço.  Entre as crianças de 5 a 11 anos, 39,00% já receberam uma dose da vacina.",
                "https://www.goias.gov.br/images/2020/2022_01_28_COVID_Adriano_Machado.jpg",
                "GO",
                "30/03/2022",
                "416.740"),
            Noticia(11,"No Amapá, casos recuperados da Covid-19 chegam a 63%",
                "O percentual representa 19.372 pessoas recuperadas dos mais de 30 mil casos registrados até o momento no estado.",
                "Dados do último boletim epidemiológico, divulgado nesta quarta-feira (8), apontam que a taxa de recuperação de infectados pela covid-19 chegou a 63,4% no Amapá. O índice, o mais alto desde a primeira contaminação no Estado, representa 19.372 pessoas recuperadas da doença entre os 30.524 casos positivos registrados até o momento. Segundo o secretário de Estado da Saúde, Juan Mendes, a alta taxa de recuperação é resultado de um conjunto de medidas adotadas pelo Governo do Amapá, como a criação de cinco centros para tratamento da doença, adoção de protocolos médicos eficazes, aquisição de equipamentos e insumos, parceria com as prefeituras dos municípios, entre outras.",
                "https://corona.portal.ap.gov.br/storage/news/ekyilMjeC4M6HEYfMqYIhLS9yFB9OJxsMGFbhhlL.jpeg",
                "AP",
                "09/07/2020",
                "415.645"),
            Noticia(12,"Operação Gratidão: Amazonas recebe mais três pacientes vindos de Rondônia para tratamento da Covid-19",
                "O Amazonas recebeu, na tarde desta sexta-feira (19/03), mais dois pacientes vindos do Estado de Rondônia para dar continuidade ao tratamento de Covid-19 em Manaus. O outro paciente, também de Rondônia, chegou na noite de quinta-feira (18/03).",
                "Os dois pacientes, do sexo masculino, com 71 e 53 anos, desembarcaram no aeroclube de Manaus e foram encaminhados, em Unidade de Terapia Intensiva (UTI) móvel, para o Hospital Delphina Aziz, referência no tratamento da doença no Estado. E o terceiro paciente, um homem de 26 anos, também de Rondônia, já havia sido transferido para Manaus na noite de quinta-feira (18/03). “Mais uma emoção. Resume-se em solidariedade. Estamos aqui de portas abertas com a solidariedade, agradecendo tudo o que o Brasil fez por nós. Estamos aqui tentando devolver o amor da vida de alguém ao seu domicílio”, resumiu a enfermeira e coordenadora da rede de atenção à saúde da Secretaria de Estado de Saúde do Amazonas (SES-AM), Neylane Macêdo.",
                "http://coronavirus.amazonas.am.gov.br/wp-content/uploads/2021/03/Opera%C3%A7%C3%A3o-Gratid%C3%A3o-Covid-19-Pacientes-Rond%C3%B4nia.jpeg",
                "AM",
                "19/03/2021",
                "410.480"),
            Noticia(13,"Covid-19: Aplicação da 4ª dose da vacina para idosos com 80 anos ou mais começa na quinta-feira em Salvador",
                "Idoso deve ter tomado a dose de reforço até 30 de novembro de 2021.",
                "A Prefeitura de Salvador, através da Secretaria Municipal da Saúde (SMS), inicia a aplicação da 4ª dose da vacina contra a Covid-19 para idosos com idade igual ou superior a 80 anos, na quinta-feira (31). Para ter acesso ao imunizante, o idoso deve ter um intervalo de quatro meses do recebimento da dose de reforço, ou seja, estão habilitados aqueles que tomaram até 30 de novembro de 2021. A ação acontece das 8h às 16h. A abertura do novo ciclo será realizada pelo titular da pasta, Decio Martins, a partir das 11h, na Instituição de Longa Permanência para Idosos (ILPI) Santa Clara, no bairro de Brotas, com a imunização coletiva de 30 idosos residentes do local. Outras casas de repouso da capital baiana também serão contempladas com a vacinação ao longo dos próximos dias.",
                "https://s2.glbimg.com/s2F5J32U0Xan5sybttxkqyR9dOg=/0x0:1500x1000/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/i/F/AongYuTcCBBjfUTjgnGQ/30-08-21-vacinacao-terceira-dose-idosos-foto-igor-santos-secom-pms-8.jpg",
                "BA",
                "30/03/2022",
                "406.254"),
            Noticia(14,"Camilo Santana anuncia novo decreto de combate a Covid-19 no Ceará",
                "Documento flexibiliza uso obrigatório de máscara de proteção em ambientes abertos a partir de segunda-feira",
                """O governador do Ceará Camilo Santana (PT) anunciou, nesta sexta-feira (18), o novo decreto de enfrentamento à pandemia. O documento desobriga o uso o obrigatório de máscara em ambientes abertos do Estado a partir de segunda-feira (21).  O decreto com detalhes da medida será publicado neste sábado (19).O anúncio foi feito ao lado do prefeito de Fortaleza, José Sarto (PDT), e do secretário da Saúde do Estado, Marcos Gadelha.""",
                "https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3205878:1647613232/Camilo.jpg?f=16x9&h=720&w=1280&$p$f$h$w=fb93a93",
                "CE",
                "18/03/2022",
                "405.152"),
            Noticia(15,"Covid-19: shows e eventos no ES não terão mais limitação de público",
                "Governador Renato Casagrande fez anúncio na tarde desta quarta (30). Autorização decorreu da melhoria nas condições da pandemia da Covid-19, com consolidação na queda de casos e óbitos pela doença",
                "Para compartilhar esse conteúdo, por favor utilize o link https://www.agazeta.com.br/es/cotidiano/covid-19-shows-e-eventos-no-es-nao-terao-mais-limitacao-de-publico-0322 ou utilize os recursos oferecidos na página. Textos, fotos, artes e vídeos da Rede Gazeta estão protegidos pela legislação brasileira sobre direito autoral. Não reproduza o conteúdo digital e/ou do jornal em qualquer meio de comunicação, eletrônico ou impresso, sem autorização da Rede Gazeta (agenciaag@redegazeta.com.br). As regras têm como objetivo proteger o investimento que a Rede Gazeta faz para produzir um conteúdo jornalístico de qualidade.",
                "https://midias.agazeta.com.br/2022/02/25/710x388/o-governador-renato-casagrande-710230.jpg",
                "ES",
                "30/03/2022",
                "404.874"),
            Noticia(16,"GOVERNO CONTABILIZA MAIS DE 53 MIL ATENDIMENTOS EM DOIS ANOS DE CENTRO DE TESTAGEM",
                "Um dos primeiros Centro de Testagem para Covid-19 do Governo do Estado já ultrapassou os 53 mil atendimentos.",
                "Funcionando atualmente no Hospital Genésio Rego, na Vila Palmeira, o equipamento foi inaugurado pela Secretaria de Estado da Saúde (SES) em março de 2020, como parte das ações do poder público estadual para ampliar a testagem para diagnóstico da Covid-19. O serviço teve início na Avenida Beira-Mar e também funcionou no Hospital de Cuidados Intensivos (HCI). A testagem segue disponível no Hospital Genésio Rego, exclusiva para idosos a partir de 60 anos, pessoas com doenças crônicas, pessoas com deficiência e profissionais da educação, da saúde e da segurança na ativa.",
                "https://www.saude.ma.gov.br/wp-content/uploads/2022/03/35886_centro_de_testagem_1_2329119615486811509.jpeg",
                "MA",
                "24/03/2022",
                "400.673"),
            Noticia(17,"Mato Grosso registra 726.156 casos e 14.866 óbitos por Covid-19",
                "A Secretaria de Estado de Saúde (SES-MT) notificou, até a tarde desta quarta-feira (30.03), 726.156 casos confirmados da Covid-19 em Mato Grosso, sendo registrados 14.866 óbitos em decorrência do coronavírus no Estado.",
                "Foram notificadas 531 novas confirmações de casos de coronavírus no Estado. Dos 726.156 casos confirmados da Covid-19 em Mato Grosso, 543 estão em isolamento domiciliar e 710.172 estão recuperados. Entre casos confirmados, suspeitos e descartados para a Covid-19, há 59 internações em UTIs públicas e 39 em enfermarias públicas. Isto é, a taxa de ocupação está em 24,39% para UTIs adulto e em 9% para enfermaria adulta.",
                "http://www.saude.mt.gov.br/upload/noticia/1/imagem/300322180842.jpg",
                "MT",
                "30/03/2022",
                "400.141"),
            Noticia(18,"Em novo boletim, MS registra queda de casos e internações por Covid",
                "Mato Grosso do Sul segue registrando queda em alguns indicadores da Covid.",
                "Com 214 novos casos no boletim epidemiológico desta quarta-feira (30), a média móvel de casos que ontem era de 361, hoje está em 300. Outro indicador em gradativa redução é o de hospitalizados. O gráfico que aponta a evolução de casos em internação no Estado mostra que no dia 11 de março haviam 139 pessoas internadas pela Covid, e hoje são 45. São 17 em leitos clínicos e 28 em leitos de UTI.",
                "http://www.ms.gov.br/wp-content/uploads/sites/150/2022/03/Vacina%C3%A7%C3%A3o-foto-Saul-Schramm-730x425.jpg",
                "MS",
                "30/03/2022",
                "398.571"),
            Noticia(19,"Governo de Minas vai destinar R$ 1,8 milhão para retomada de seis obras de UBS no Centro-Oeste",
                "Em Divinópolis, governador destacou investimentos recorde na Saúde na cidade e região",
                "O governador Romeu Zema e o secretário de Estado de Saúde, o médico Fábio Baccheretti, estiveram, nesta quinta-feira (24/3), na Superintendência Regional de Saúde em Divinópolis para verificar os trabalhos feitos na unidade. A regional atende 53 municípios e é a segunda mais populosa do estado.",
                "https://www.saude.mg.gov.br/images/1_noticias/08_2022/04-jan-fev-mar/24-03_Dirceu_Aurelio.jpg",
                "MG",
                "24/03/2022",
                "390.235"),
            Noticia(20,"Casos de coronavírus na Paraíba em 30 de março de 2022",
                "Paraíba tem 595.932 casos confirmados e 10.192 mortes por coronavírus. São 585 novos casos e uma morte computados nas últimas 24 horas.",
                "A Paraíba tem 595.932 casos confirmados de contaminação pelo novo coronavírus, segundo informações da Secretaria de Estado da Saúde (SES), divulgadas nesta quarta-feira (30). O número de mortes confirmadas por Covid-19 é de 10.192 no estado desde o início da pandemia. São 585 novos casos e uma morte foram computados nas últimas 24 horas. A ocupação total de leitos de UTI na Paraíba é de 15%. Em João Pessoa, o percentual é de 37%. Em Campina Grande, 2% dos leitos estão ocupados. Já a ocupação no Sertão é 18%.",
                "https://s2.glbimg.com/MKj6p93e5duBEVnFQ3unHVvaUaI=/0x0:1280x960/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/W/2/HzOvIWSAaWu8wG0ZZaHg/complexo-reativa-12-leitos-de-enfermaria-covid-no-hospital-noaldo-leite-para-enfrentar-aumento-de-casos-da-doenca.jpg",
                "PB",
                "30/03/2022",
                "388.439"),
            Noticia(21,"Estado recebe vacinas contra a Covid-19 para dose de reforço",
                "A Secretaria de Estado da Saúde (Sesa) recebeu nesta quarta-feira (30) mais 17.250 vacinas da Janssen destinadas para a dose de reforço para a população acima de 18 anos. ",
                "Os imunizantes desembarcaram no Aeroporto Internacional Afonso Pena, em São José dos Pinhais, na Região Metropolitana de Curitiba, e foram encaminhados para o Centro de Medicamentos do Paraná (Cemepar) onde passarão por conferência e armazenamento, até que sejam distribuídos. “Continuamos a receber vacinas para reforço. Iniciamos a vacinação da 4ª dose nos idosos acima de 80 anos, mas é importante também que os mais novos recebam suas primeiras doses de reforço”, disse o secretário de Estado da Saúde, Beto Preto. Além dos imunizantes, o Governo do Estado também foi contemplado com mais 660.000 seringas descartáveis de 0,3ml com agulha 23Gx1, necessária para o manuseio das vacinas da Pfizer (adulto) e 220.000 seringas descartáveis de 0,5ml com agulha 23Gx1, indicada para as vacinas AstraZeneca/CoronaVac/Janssen.",
                "https://www.saude.pr.gov.br/sites/default/arquivos_restritos/files/imagem/2022-03/e13914c6-15e7-41fe-a1db-b9621ea6bc1c.jpg",
                "PR",
                "30/03/2022",
                "385.756"),
            Noticia(22,"Governo de Pernambuco libera uso de máscaras em locais abertos a partir desta terça-feira (29)",
                "Também está liberada a realização de eventos com 100% do público, incluindo shows, festas e estádios de futebol",
                """A partir desta terça-feira (29), não será mais obrigatório o uso de máscaras em ambientes abertos em Pernambuco. Também está liberada a realização de eventos com 100% do público, incluindo shows, festas e estádios de futebol. A flexibilização foi anunciada no início da tarde desta segunda-feira (28) pelo governador Paulo Câmara. Segundo o Gabinete de Enfrentamento à Covid-19, a decisão é baseada nos recentes dados de saúde do Estado, que registraram, no último sábado (26), a sétima semana consecutiva de queda nos índices da doença no Estado. Além dos casos, óbitos e solicitações de vagas em UTI estarem em patamares baixos, o índice de positividade nos exames processados chegou a 0,95%, menor número desde o início da pandemia, de acordo com o Governo de Pernambuco.""",
                "https://cdn.folhape.com.br/img/pc/1100/1/dn_arquivo/2021/11/montagem-1100-x-600-51_1.jpg",
                "PE",
                "28/03/22",
                "384.295"),
            Noticia(23,"Uso de máscaras e passaporte de vacina continuam obrigatórios para ingresso na Defensoria Pública do Piauí",
                "Objetivo é garantir a máxima proteção à população e equipes da Instituição, considerando que mesmo com a redução dos índices a pandemia permanece e o expediente na Defensoria ocorre em ambiente fechado",
                """O uso de máscaras continua sendo obrigatório para ingresso e permanência nas dependências da Defensoria Pública do Estado do Piauí, tanto na capital como no interior do Estado. Também é necessária a apresentação do comprovante de vacinação contra a covid-19 para ingresso nos prédios da Instituição. As medidas constam na Portaria Conjunta GDPG/CG Nº 013/2022, que estabelece o retorno integral das atividades presenciais na Defensoria, a partir do dia 4 de abril de 2022, observadas as medidas de prevenção ao contágio pelo coronavírus. O documento é assinado pelo defensor público geral, Erisvaldo Marques dos Reis e pelo corregedor-geral, Francisco de Jesus Barbosa. Ao determinar a obrigatoriedade do uso de máscaras na Defensoria Pública, assim como a apresentação do passaporte de vacina contra a covid-19 para ter ingresso às dependências da Defensoria tanto em Teresina como no interior do Piauí, foi considerada a autonomia funcional e administrativa da Instituição bem como que o avanço da vacinação tem se revelado de fundamental importância  na proteção contra a covid-19 e redução das hospitalizações e mortes.  Considera-se ainda o Decreto Nº 20.525, de 01 de fevereiro de 2022, do Governo do Estado que trata sobre a obrigatoriedade de máscara de proteção facial no Piauí.""",
                "https://www.pi.gov.br/wp-content/uploads/2022/03/atendimento-defensoria-1-730x799.jpg",
                "PI",
                "29/03/2022",
                "382.905"),
            Noticia(24,"Com redução de casos de covid-19, hospitais de Porto Alegre começam a ampliar visitas",
                "Em alguns locais, o acesso estava limitado desde o início da pandemia, em função do risco de transmissão",
                "A queda nos casos e internações por covid-19 está permitindo que alguns hospitais de Porto Alegre comecem a flexibilizar a política de visitantes. Há locais em que o acesso estava limitado desde o início da pandemia, em razão do risco de transmissão. Nesta semana, o Hospital Ernesto Dornelles liberou as visitas nas unidades de Internação e de Cuidados Especiais mediante o cumprimento de regras, como a presença de uma pessoa por paciente. Segundo a instituição, este tipo de liberação só estava ocorrendo nas unidades de terapia intensiva e na emergência.",
                "https://conteudo.imguol.com.br/c/noticias/b4/2021/03/03/escalada-de-internacoes-e-mortes-causadas-pela-covid-19-nas-ultimas-semanas-causa-sobrecarga-no-sistema-de-saude-de-porto-alegre-1614812165249_v2_900x506.jpg.webp",
                "RS",
                "29/03/2022",
                "377.992"),
            Noticia(25,"Pela primeira vez na pandemia, maior hospital de Roraima zera internações em todos os leitos para Covid",
                "Administrado pelo governo, Hospital Geral de Roraima é a unidade para casos graves da doença e, neste dois anos de pandemia, registrou superlotação e pacientes no corredor.",
                "Pela primeira vez em dois anos de pandemia, o Hospital Geral de Roraima (HGR), maior unidade pública do estado, não tem pacientes com Covid internados. Os leitos clínicos e de UTI foram zerados nessa terça-feira, divulgou a Secretaria de Saúde (Sesau). No boletim epidemiológico sobre a Covid divulgado diariamente pela Sesau mostra a taxa de ocupação em 0%, um feito inédito até então na unidade.",
                "https://s2.glbimg.com/pT5OVI2czH51GZ4LdegfUNaHM94=/0x0:1000x516/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/s/R/uALNanQkyr2K0OWTzgTA/foto-2.png",
                "RR",
                "30/03/2022",
                "378.843"),
            Noticia(26,"Dia estadual de homenagem às vítimas da Covid-19: Rondônia já perdeu mais de 7 mil pessoas para a doença",
                "Lei estadual estabeleceu 29 de março como dia em memória às vítimas da pandemia em Rondônia. Confira histórias — para além dos números.",
                "Há exatamente dois anos, familiares, amigos e a população de Rondônia lamentavam a primeira morte por Covid-19 no estado. Esta terça-feira (29) é marcada pelo dia estadual em homenagem às 7.175 vidas perdidas pela doença desde o início da pandemia. Uma das vítimas foi Maryluce Ferreira. Ela faleceu aos 38 anos, em 10 de maio de 2020, Dia das Mães. Segundo o irmão, Thiago Gonçalves, ela era funcionária pública, se doava pela cultura rondoniense e sempre tinha um sorriso no rosto de orelha a orelha.",
                "https://s2.glbimg.com/8J5pdoimXTZKXZTBF9v_RweWD40=/0x0:1366x768/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/g/V/GBuWJQT0iPPP0LbcxMRw/cemiterio-porto-velho.jpg",
                "RO",
                "29/03/2022",
                "365.904"),
            Noticia(27,"Coronavírus em SC: Estado confirma 1.673.157 casos, 1.647.319 recuperados e 21.656 mortes",
                "O Governo do Estado informou que há 1.673.157 casos confirmados de Covid-19, sendo que 1.647.319 se recuperaram e 4.182 estão em acompanhamento.",
                "O balanço foi divulgado nesta terça-feira, 29. Desde o início da pandemia, 21.656 mortes foram causadas pelo coronavírus. Esses números colocam a taxa de letalidade em 1,29%. São 106 casos ativos a mais em comparação com o último boletim, e há 5 óbitos adicionais. Aos casos confirmados se somaram 1.816, enquanto a estimativa de recuperados subiu 1.705.",
                "https://s2.glbimg.com/c34OOuu8KN3Qxi64goOMpgScQwQ=/0x0:3605x2604/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/i/p/KIdNAYTmaGeawFbGO3hQ/000-1rf9oj.jpg",
                "SC",
                "29/03/2022",
                "354.872"),
            Noticia(28,"Sergipe registra 167 novos casos conhecidos de Covid-19 e duas mortes",
                "Desde o início da pandemia, 325.778 pessoas testaram positivo para a doença e 6.315 morreram.",
                "Nesta quarta-feira (30), Sergipe registrou 167 novos casos conhecidos de Covid-19 e duas mortes. A informação foi divulgada pela Secretaria da Saúde de Sergipe (SES). Os dois óbitos confirmados foram: uma mulher, 88 anos, de Aracaju, com Alzheimer e hipertensão; uma mulher, 48 anos, de Nossa Senhora do Socorro, com HIV.",
                "https://s2.glbimg.com/RjoGZI1JG7PPhzBGlr8a08jycHU=/0x0:1700x1065/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/0/9/cjYBdDRremv0ADi4s2ZA/lacen.jpg",
                "SE",
                "30/03/2022",
                "352.930"),
            Noticia(29,"Tocantins recebe mais 3,5 mil vacinas AstraZeneca para combate à Covid-19",
                "Governo do Estado recebeu nesta quarta-feira, 24, a quinta remessa de imunizantes que serão destinados a todos os municípios tocantinenses",
                "Na manhã desta quarta-feira, 24, chegou a Palmas, a quinta remessa de imunizantes para combate à Covid-19, encaminhada pelo Ministério da Saúde (MS). As 3,5 mil vacinas AstraZeneca recebidas pelo Governo do Tocantins, por meio da Secretaria de Estado da Saúde (SES), serão distribuídas a todos os municípios tocantinenses. O gestor da SES, Edgar Tollini, esclarece que as doses são primordiais para a conclusão da primeira fase da imunização no Tocantins. “Estas vacinas já eram aguardadas e fazem parte do nosso planejamento para o término da imunização da população que integra o primeiro grupo prioritário”, afirmou o secretário.",
                "https://central.to.gov.br/image/188302?w=883&h=505",
                "TO",
                "24/03/2022",
                "348.294"),
            Noticia(30,"Número de internações por COVID-19 caiu 84% desde janeiro em SP",
                "Estado está há oito semanas seguidas com queda nas novas internações",
                "O Governador João Doria anunciou nesta quarta-feira (30) que o Estado de São Paulo registrou redução de 84% das internações por COVID-19 desde o final de janeiro, quando foi registrado o pico da variante Ômicron. Atualmente os hospitais possuem 1.869 pacientes internados, sendo 1.195 em enfermaria e 672 em UTI (Unidade de Terapia Intensiva). “É uma notícia para ser celebrada. As internações vêm caindo há oito semanas e hoje, pelo quinto dia seguido, São Paulo tem menos de 2 mil pessoas internadas em UTI e em enfermaria”, disse Doria.",
                "https://live.staticflickr.com/65535/51971536128_db874521ae_b.jpg",
                "SP",
                "30/03/2022",
                "342.451"),
            Noticia(31,"Governo de SP entrega complexo de nova fábrica de vacinas do Butantan",
                "Com investimento de R$ 189 milhões obtido 100% com doações privadas, nova planta terá capacidade para 100 milhões de vacinas anuais",
                "O Governador João Doria participou nesta sexta-feira (25) da entrega do complexo da nova fábrica de vacinas do Instituto Butantan contra a Covid-19. O Centro de Produção Multipropósito de Vacinas terá capacidade de produzir 100 milhões de doses por ano e foi construída com R$ 189 milhões doados totalmente pela iniciativa privada. Além da Coronavac, a fábrica também vai ampliar a produção atual de vacinas contra raiva, zika e hepatite A. “É uma fábrica 100% digital e sustentável e que vai gerar cerca de 130 empregos diretos com engenheiros, especialistas de todas as idades, homens e mulheres”, afirmou Doria. “Esta fábrica é uma vitória de São Paulo e do Brasil. São Paulo apoia, respeita e prestigia a ciência e já ofereceu a vacina a mais de 120 milhões de braços”, afirmou",
                "https://live.staticflickr.com/65535/51960768394_6856af70dd_h.jpg",
                "SP",
                "25/03/2022",
                "341.874"),
            Noticia(32,"Rio dá continuidade à vacinação da população e testagem de pessoas com sintomas gripais",
                "Todas as pessoas com 5 anos ou mais podem receber a primeira dose da vacina contra a covid-19. ",
                "As unidades seguem realizando a segunda aplicação da vacina, considerando o intervalo a partir da data da primeira dose, e a aplicação da dose de reforço continua para pessoas com 18 anos ou mais que tomaram a segunda dose há pelo menos 4 meses. Crianças com deficiência e/ou comorbidades podem antecipar a segunda dose da Pfizer pediátrica para o intervalo mínimo de 21 dias.",
                "https://coronavirus.rio/wp-content/uploads/2021/11/51407091694_e9b881cc0e_w.jpg",
                "RJ",
                "02/03/2022",
                "340.872"),
            Noticia(33,"Com baixa dos casos, centro de testagem do Leblon é encerrado",
                "Com a redução da procura da população por testes para covid-19 e a baixa na taxa de positividade para a doença, que atingiu na quarta-feira (16) o menor índice do ano, 6,8%, a Secretaria Municipal de Saúde (SMS-Rio) encerrará neste sábado (19) as atividades do centro de atendimento e testagem do Ciep Nação Rubro Negra, no Leblon.",
                "A partir da próxima segunda-feira (21), quem precisar fazer o teste poderá procurar o Centro Municipal de Saúde Píndaro de Carvalho Rodrigues, na Gávea, que fica a cerca de 400 metros do Ciep e funciona de segunda a sexta-feira, das 8h às 17h, e aos sábados, das 8h ao meio-dia. Ao todo, a SMS-Rio chegou a abrir 23 centros de testagem desde dezembro (três deles em parceria com a Fiocruz e três com as Forças Armadas), para atender à alta da demanda devido ao surto da gripe H3N2 no final do ano passado e à introdução da variante ômicron da covid-19 na cidade, em janeiro. Desse total, após o encerramento do polo do Leblon, 11 ainda estarão abertos, mas com a queda dos índices da doença na cidade, serão desmobilizados gradualmente até março.",
                "https://coronavirus.rio/wp-content/uploads/2022/02/20220107101159__MG_1444.jpg",
                "RJ",
                "18/02/2022",
                "389.745")
        ]


    def listar_noticia(self):
        return self.noticia

    def randomizar1(self):
        return self.noticia[random.randint(0,10)]

    def randomizar2(self):
        return self.noticia[random.randint(10,20)]

    def randomizar3(self):
        return self.noticia[random.randint(20,33)]

    def segunda_noticia(self):
        return self.noticia[random.randint(0,len(self.noticia)-1)]

    def noticia_estado(self,estado):
        return self.noticia[int(estado)]

    def noticia_titulo(self, id):
        return self.noticia[int(id)].get__titulo

    def noticia_id(self,id):
        return self.noticia[int(id)]

    def comentar(self, avaliacao, id):
        self.comentarios.append(Noticia(avaliacao, self.noticia_id(id)))
        return self.comentarios

class ComentarioDao:
    def lista_comentario(self):
        return comentario

    def inserir(self, avaliacao, link):
        avaliacao.setLink(link)
        comentario.append(avaliacao)
